### PR TITLE
Use tool:pytest instead of pytest

### PR DESCRIPTION
**Pull request by scarabeusiv**
Usage of only pytest is no longer working on pytest 4.2+

### CODE REVIEW

**Review by pllim — APPROVED** [review]

**Review by drdavella — CHANGES_REQUESTED** [review]
This is fine with me, but if we do this I think we need to update the minimum required version of pytest as well (should be `3.1`, I think). It may also require us to formally drop support for Py27, which shouldn't be a problem.

**Comment by scarabeusiv** [comment]
You don't need to drop support for python 2.7, it just works there, I am applying this patch just to get the package buildable on python3.7 and python2.7 for openSUSE with pytest 4.2.

Also [tool:pytest] is supoorted since 3.0.0 pytest.

**Comment by blueyed** [comment]
Older pytest would just ignore the section then, which is fine I guess?

It is not critical for using pytest-openfiles to have the config for when running its tests.

**Comment by blueyed** [comment]
I think pytest itself should not error out, but use an existing "[tool:pytest]" section - so both could be given here then.

**Comment by bsipocz** [comment]
Based on the discussion above and the all green CI, I just go ahead and merge this.

**Pull request merged**
