### PR TITLE
MNT: Drop Python 3.6

### LINKED ISSUE #45: Drop Python 3.6
CI no longer supports it (Python 3.6 job is now broken).

### PR DESCRIPTION
**Pull request by pllim**
Drop Python 3.6 and also update CI matrix. Fix #45

### CODE REVIEW

**Comment by pllim** [comment]
Not sure what is up with Python 3.10

`TypeError: required field "lineno" missing from alias`

**Review by bsipocz — APPROVED** [review]
Honestly, as this is about to be archived, I would just stop adding the new versions. Or to, in fact, do anything as no new release is planned.

**Comment by pllim** [comment]
I do plan to do one last release before archiving (timeline TBD). The new versions are added to CI as "free upgrade". ~You see that I omitted Python 3.10 in the CI matrix because there was a CI failure I don't want to deal with...~ 🙈

**Comment by pllim** [comment]
Hmmm https://github.com/pytest-dev/pytest/discussions/9195

**Pull request merged**
